Add Friends Functionality
playgameservices/android-basic-samples pull request #309
Opened 2020-09-02 16:08 UTC by redls

Added Friends APIs: Play Games now has a cross-game Friends list. Request access to your players cross-game PGS friends list and integrate it with your in-game system to help players play with a set of high-quality gaming friends, and help people find their friends within your game. Learn more about Play Games Services .

2020-09-03 09:20 UTC, olehkuznetsov reviewed
Why do we remove android here? and previously for background?

2020-09-03 09:24 UTC, olehkuznetsov requested changes

2020-09-03 09:24 UTC, olehkuznetsov commented on ButtonClicker/build.gradle
> +    implementation "com.google.android.gms:play-services-games:20.0.0"
20.0.1?

2020-09-03 09:24 UTC, olehkuznetsov commented on ButtonClicker/src/main/res/values/styles.xml
> +        <item name="background">@color/PopupColor</item>
why it become just background and other left with android?

2020-09-03 09:24 UTC, olehkuznetsov commented on TypeANumber/src/main/java/com/google/example/games/tanc/FriendsFragment.java
> +        void onBackButtonClicked();
wrong code format

2020-09-07 11:32 UTC, olehkuznetsov commented on TypeANumber/src/main/java/com/google/example/games/tanc/MainActivity.java
> +    mGoogleSignInClient =
Do we need this change?

2020-09-07 13:29 UTC, redls commented on TypeANumber/src/main/java/com/google/example/games/tanc/MainActivity.java
> +    mGoogleSignInClient =
fixed

2020-09-07 14:10 UTC, merged